#!/bin/bash
# 修改系统最大进程limit
cat > /etc/security/limits.d/20-nproc.conf <<'EOF'
# Default limit for number of user's processes to prevent
# accidental fork bombs.
# See rhbz #432903 for reasoning.
 
#nproc
*          soft    nproc     965535
root       soft    nproc     unlimited
*          hard    nproc     965535
root       hard    nproc     unlimited
#nofile
*          soft    nofile     965535
*          hard    nofile     965535
EOF

# 修改systemd系统级ulimit
cat >> /etc/systemd/system.conf <<'EOF'
DefaultLimitCORE=infinity
DefaultLimitNOFILE=9000000
DefaultLimitNPROC=9000000
EOF
 
# 修改systemd用户级ulimit
cat >> /etc/systemd/user.conf <<'EOF'
DefaultLimitCORE=infinity
DefaultLimitNOFILE=9000000
DefaultLimitNPROC=9000000
EOF
 
systemctl daemon-reload


